// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    AppBanner: typeof import('./src/components/app-banner/AppBanner.vue')['default']
    AppButton: typeof import('./src/components/app-button/AppButton.vue')['default']
    'AppButton.story': typeof import('./src/components/app-button/AppButton.story.vue')['default']
    AppFocusable: typeof import('./src/components/app-focusable/AppFocusable.vue')['default']
    AppIcon: typeof import('./src/components/app-icon/AppIcon.vue')['default']
    AppInputAppender: typeof import('./src/components/app-input-appender/AppInputAppender.vue')['default']
    AppLoader: typeof import('./src/components/app-loader/AppLoader.vue')['default']
    AppMenu: typeof import('./src/components/app-menu/AppMenu.vue')['default']
    AppMenuDivider: typeof import('./src/components/app-menu/AppMenuDivider.vue')['default']
    AppMenuItem: typeof import('./src/components/app-menu/AppMenuItem.vue')['default']
    AppModal: typeof import('./src/components/app-modal/AppModal.vue')['default']
    AppModalContent: typeof import('./src/components/app-modal/AppModalContent.vue')['default']
    AppModalOverlay: typeof import('./src/components/app-modal/AppModalOverlay.vue')['default']
    AppModalTitle: typeof import('./src/components/app-modal/AppModalTitle.vue')['default']
    AppModalWrapper: typeof import('./src/components/app-modal/AppModalWrapper.vue')['default']
    AppNotification: typeof import('./src/components/app-notifications/AppNotification.vue')['default']
    AppNotifications: typeof import('./src/components/app-notifications/AppNotifications.vue')['default']
    AppPopover: typeof import('./src/components/app-popover/AppPopover.vue')['default']
    AppTab: typeof import('./src/components/app-tabs/AppTab.vue')['default']
    AppTable: typeof import('./src/components/app-table/AppTable.vue')['default']
    AppTableTd: typeof import('./src/components/app-table/AppTableTd.vue')['default']
    AppTableTh: typeof import('./src/components/app-table/AppTableTh.vue')['default']
    AppTableTr: typeof import('./src/components/app-table/AppTableTr.vue')['default']
    AppTabs: typeof import('./src/components/app-tabs/AppTabs.vue')['default']
    AppToasts: typeof import('./src/components/app-toast/AppToasts.vue')['default']
    FormCheckbox: typeof import('./src/components/form-checkbox/FormCheckbox.vue')['default']
    FormInput: typeof import('./src/components/form-input/FormInput.vue')['default']
    'FormInput.story': typeof import('./src/components/form-input/FormInput.story.vue')['default']
    FormInputLabel: typeof import('./src/components/form-input/FormInputLabel.vue')['default']
    FormLabel: typeof import('./src/components/form-label/FormLabel.vue')['default']
    FormRadio: typeof import('./src/components/form-radio/FormRadio.vue')['default']
    FormSelect: typeof import('./src/components/form-select/FormSelect.vue')['default']
    FormSelectOption: typeof import('./src/components/form-select/FormSelectOption.vue')['default']
    FormSwitch: typeof import('./src/components/form-switch/FormSwitch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Test: typeof import('./src/Test.vue')['default']
  }
}
