// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./src/App.vue')['default']
    AppButton: typeof import('./src/components/app-button/AppButton.vue')['default']
    AppFocusable: typeof import('./src/components/app-focusable/AppFocusable.vue')['default']
    AppIcon: typeof import('./src/components/app-icon/AppIcon.vue')['default']
    AppInputAppender: typeof import('./src/components/app-input-appender/AppInputAppender.vue')['default']
    AppLoader: typeof import('./src/components/app-loader/AppLoader.vue')['default']
    AppModal: typeof import('./src/components/app-modal/AppModal.vue')['default']
    AppModalAction: typeof import('./src/components/app-modal/AppModalAction.vue')['default']
    AppModalContent: typeof import('./src/components/app-modal/AppModalContent.vue')['default']
    AppModalOverlay: typeof import('./src/components/app-modal/AppModalOverlay.vue')['default']
    AppModalTitle: typeof import('./src/components/app-modal/AppModalTitle.vue')['default']
    AppModalWrapper: typeof import('./src/components/app-modal/AppModalWrapper.vue')['default']
    AppPopover: typeof import('./src/components/app-popover/AppPopover.vue')['default']
    AppTable: typeof import('./src/components/app-table/AppTable.vue')['default']
    AppTableTd: typeof import('./src/components/app-table/AppTableTd.vue')['default']
    AppTableTh: typeof import('./src/components/app-table/AppTableTh.vue')['default']
    AppTableTr: typeof import('./src/components/app-table/AppTableTr.vue')['default']
    AppToast: typeof import('./src/components/app-toast/AppToast.vue')['default']
    AppToasts: typeof import('./src/components/app-toast/AppToasts.vue')['default']
    FormCheckbox: typeof import('./src/components/form-checkbox/FormCheckbox.vue')['default']
    FormInput: typeof import('./src/components/form-input/FormInput.vue')['default']
    FormInputLabel: typeof import('./src/components/form-input/FormInputLabel.vue')['default']
    FormLabel: typeof import('./src/components/form-label/FormLabel.vue')['default']
    FormRadio: typeof import('./src/components/form-radio/FormRadio.vue')['default']
    FormSwitch: typeof import('./src/components/form-switch/FormSwitch.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
